name: Update Stable Docs

on:
  release:
    types: [published]
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update_stable_docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git user
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"

    - name: Check if stable-docs branch exists
      run: |
        if ! git rev-parse --verify stable-docs > /dev/null 2>&1; then
          git checkout -b stable-docs
          git push -u origin stable-docs
        fi

    - name: Handle Release
      if: github.event_name == 'release'
      run: |
        git fetch --all
        git checkout stable-docs
        git reset --hard ${GITHUB_REF#refs/tags/}
        git push origin stable-docs --force

    - name: Handle Commit to Main
      if: contains(github.event.head_commit.message, '!stable-docs')
      run: |
        git fetch --all
        git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '^docs/' > changes.txt
        if [[ -s changes.txt ]]; then
          git checkout stable-docs
          git checkout ${{ github.sha }} -- $(cat changes.txt)
          git commit -m "Cherry-picked docs changes from ${{ github.sha }}"
          git push origin stable-docs
        fi
